!> Unit tests for the XC table I/O module
!!
!! These tests are self-contained: every table they read is generated by the
!! test itself in a scratch directory under build/ and removed afterwards.
!!
!! Rationale: generated fixtures keep the I/O tests meaningful without requiring
!! a checked-in table directory.
program test_table_io
    use fortuno_serial, only: execute_serial_cmd_app, check_failed => serial_check_failed
    implicit none

    call execute_serial_cmd_app(get_table_io_tests())

contains

    function get_table_io_tests() result(tests)
        use fortuno_serial, only: test_list, test => serial_case_item
        type(test_list) :: tests

        tests = test_list([ &
            test("read_cpp_u4", test_read_cpp_u4), &
            test("extract_u_standard", test_extract_u_standard), &
            test("extract_u_binary", test_extract_u_binary), &
            test("extract_u_invalid", test_extract_u_invalid), &
            test("table_filename_roundtrip", test_table_filename_roundtrip), &
            test("binary_roundtrip", test_binary_roundtrip), &
            test("table_dimensions", test_table_dimensions), &
            test("table_ranges", test_table_ranges), &
            test("missing_file", test_missing_file), &
            test("missing_file_roundtrip_is_safe", test_missing_file_roundtrip_is_safe), &
            test("deallocate_table", test_deallocate_table), &
            test("multiple_tables", test_multiple_tables), &
            test("write_rejects_nonfinite", test_write_rejects_nonfinite) &
        ])
    end function get_table_io_tests

    ! write_fortran_table must refuse a table with a NaN or an Inf anywhere in
    ! exc/vxc_up/vxc_down: no file, ERROR_NOT_A_NUMBER. Each array is probed
    ! separately, with +Inf, -Inf and NaN, so that a check on ieee_is_nan alone
    ! (which lets ±Inf through) fails this test.
    subroutine test_write_rejects_nonfinite()
        use fortuno_serial, only: check => serial_check
        use table_io
        use lsda_constants, only: dp
        use lsda_errors, only: ERROR_NOT_A_NUMBER, ERROR_SUCCESS
        use, intrinsic :: ieee_arithmetic, only: ieee_value, ieee_quiet_nan, &
            ieee_positive_inf, ieee_negative_inf

        character(len=*), parameter :: bin_file = "build/test_tmp/nonfinite_table_u4.00.dat"
        type(xc_table_t) :: table
        real(dp) :: bad(3)
        integer :: status, n_exc, n_up, n_dn, which_array, which_value
        logical :: exists

        bad(1) = ieee_value(0.0_dp, ieee_quiet_nan)
        bad(2) = ieee_value(0.0_dp, ieee_positive_inf)
        bad(3) = ieee_value(0.0_dp, ieee_negative_inf)

        call ensure_scratch_dir()
        call remove_file(bin_file)

        do which_array = 1, 3
            do which_value = 1, 3
                call make_finite_table(table)
                select case (which_array)
                case (1); table%exc(2, 2)      = bad(which_value)
                case (2); table%vxc_up(1, 3)   = bad(which_value)
                case (3); table%vxc_down(3, 1) = bad(which_value)
                end select

                call count_nonfinite_entries(table, n_exc, n_up, n_dn)
                call check(n_exc + n_up + n_dn == 1, &
                    "exactly one non-finite entry should be counted")
                call check(merge(n_exc, merge(n_up, n_dn, which_array == 2), which_array == 1) == 1, &
                    "the non-finite entry should be attributed to the right array")

                call write_fortran_table(bin_file, table, status)
                call check(status == ERROR_NOT_A_NUMBER, &
                    "write_fortran_table must return ERROR_NOT_A_NUMBER for a non-finite table")
                inquire(file=bin_file, exist=exists)
                call check(.not. exists, "no file may be created for a non-finite table")

                call deallocate_table(table)
                call remove_file(bin_file)
            end do
        end do

        ! Control: the same table with every entry finite is written.
        call make_finite_table(table)
        call count_nonfinite_entries(table, n_exc, n_up, n_dn)
        call check(n_exc + n_up + n_dn == 0, "a finite table has no non-finite entries")
        call write_fortran_table(bin_file, table, status)
        call check(status == ERROR_SUCCESS, "a finite table must be written")
        inquire(file=bin_file, exist=exists)
        call check(exists, "the finite table file must exist")
        call deallocate_table(table)
        call remove_file(bin_file)
    end subroutine test_write_rejects_nonfinite

    ! A tiny 3x3 table with arbitrary finite values.
    subroutine make_finite_table(table)
        use table_io, only: xc_table_t
        use lsda_constants, only: dp
        type(xc_table_t), intent(out) :: table
        integer :: i, j

        table%U = 4.0_dp
        table%n_points_n = 3
        table%n_points_m = 3
        allocate(table%n_grid(3), table%m_grid(3, 3))
        allocate(table%exc(3, 3), table%vxc_up(3, 3), table%vxc_down(3, 3))
        do i = 1, 3
            table%n_grid(i) = 0.25_dp * real(i, dp)
            do j = 1, 3
                table%m_grid(j, i) = table%n_grid(i) * real(j - 2, dp)
                table%exc(j, i) = -0.1_dp * real(i + j, dp)
                table%vxc_up(j, i) = 0.01_dp * real(i - j, dp)
                table%vxc_down(j, i) = 0.02_dp * real(j - i, dp)
            end do
        end do
    end subroutine make_finite_table


    ! ------------------------------------------------------------------
    ! Fixture helpers
    ! ------------------------------------------------------------------

    !> Number of density blocks written by make_cpp_table_file
    integer function n_blocks_ref()
        n_blocks_ref = 50
    end function n_blocks_ref

    !> Number of magnetization rows per block written by make_cpp_table_file
    integer function n_mag_ref()
        n_mag_ref = 101
    end function n_mag_ref

    !> Reference density of block i: 0.02, 0.04, ... 1.00
    function n_ref(i) result(n_val)
        use lsda_constants, only: dp
        integer, intent(in) :: i
        real(dp) :: n_val
        n_val = real(i, dp) / real(n_blocks_ref(), dp)
    end function n_ref

    !> Reference magnetization of row j in block i: uniform grid on [0, n]
    function m_ref(j, i) result(m_val)
        use lsda_constants, only: dp
        integer, intent(in) :: j, i
        real(dp) :: m_val
        m_val = n_ref(i) * real(j - 1, dp) / real(n_mag_ref() - 1, dp)
    end function m_ref

    !> Reference XC energy: strictly negative, as a real XC table must be
    function exc_ref(j, i) result(e_val)
        use lsda_constants, only: dp
        integer, intent(in) :: j, i
        real(dp) :: e_val
        e_val = -0.5_dp * n_ref(i) * (1.0_dp - 0.25_dp * m_ref(j, i)**2)
    end function exc_ref

    !> Reference spin-up XC potential (equals vxc_down at m = 0)
    function vxc_up_ref(j, i) result(v_val)
        use lsda_constants, only: dp
        integer, intent(in) :: j, i
        real(dp) :: v_val
        v_val = -0.5_dp + 0.1_dp * n_ref(i) + 0.05_dp * m_ref(j, i)
    end function vxc_up_ref

    !> Reference spin-down XC potential (equals vxc_up at m = 0)
    function vxc_down_ref(j, i) result(v_val)
        use lsda_constants, only: dp
        integer, intent(in) :: j, i
        real(dp) :: v_val
        v_val = -0.5_dp + 0.1_dp * n_ref(i) - 0.05_dp * m_ref(j, i)
    end function vxc_down_ref

    !> Create the scratch directory used for generated fixtures
    subroutine ensure_scratch_dir()
        call execute_command_line("mkdir -p build/test_tmp")
    end subroutine ensure_scratch_dir

    !> Write a table in the legacy C++ ASCII format
    !!
    !! Layout (as consumed by read_cpp_table):
    !!   n: <density>
    !!   #mag   exc   vxc_up   vxc_down
    !!   <m> <exc> <vxc_up> <vxc_down>      (n_mag_ref() rows)
    !!   ... repeated for n_blocks_ref() densities
    !!
    !! @param[in]  filename Destination path
    !! @param[out] ok       .true. if the file was written successfully
    subroutine make_cpp_table_file(filename, ok)
        character(len=*), intent(in) :: filename
        logical, intent(out) :: ok
        integer :: unit, io_stat, i, j

        call ensure_scratch_dir()

        open(newunit=unit, file=filename, status='replace', action='write', &
             iostat=io_stat)
        if (io_stat /= 0) then
            ok = .false.
            return
        end if

        do i = 1, n_blocks_ref()
            write(unit, '(A,ES24.15)') 'n: ', n_ref(i)
            write(unit, '(A)') '#mag                    exc                     ' // &
                               'vxc_up                  vxc_down'
            do j = 1, n_mag_ref()
                write(unit, '(4ES24.15)') m_ref(j, i), exc_ref(j, i), &
                                          vxc_up_ref(j, i), vxc_down_ref(j, i)
            end do
        end do

        close(unit)
        ok = .true.
    end subroutine make_cpp_table_file

    !> Remove a file created by the tests (no-op if it does not exist)
    subroutine remove_file(filename)
        character(len=*), intent(in) :: filename
        integer :: unit, io_stat

        open(newunit=unit, file=filename, status='old', iostat=io_stat)
        if (io_stat == 0) close(unit, status='delete')
    end subroutine remove_file

    !> Return whether every allocatable table component is available
    logical function table_is_allocated(table)
        use table_io, only: xc_table_t
        type(xc_table_t), intent(in) :: table

        table_is_allocated = allocated(table%n_grid) .and. allocated(table%m_grid) .and. &
                             allocated(table%exc) .and. allocated(table%vxc_up) .and. &
                             allocated(table%vxc_down)
    end function table_is_allocated


    ! ------------------------------------------------------------------
    ! Tests
    ! ------------------------------------------------------------------

    subroutine test_read_cpp_u4()
        use fortuno_serial, only: check => serial_check
        use table_io
        use lsda_constants, only: dp

        type(xc_table_t) :: table
        integer :: status
        logical :: ok
        character(len=*), parameter :: fname = "build/test_tmp/lsda_hub_u4.00"

        call make_cpp_table_file(fname, ok)
        call check(ok, "Fixture table should be written")
        if (check_failed()) then
            call remove_file(fname)
            return
        end if

        call read_cpp_table(fname, table, status)

        call check(status == 0, "Read status should be 0")
        if (check_failed()) then
            call deallocate_table(table)
            call remove_file(fname)
            return
        end if

        call check(abs(table%U - 4.0_dp) < 1.0e-10_dp, "U should be 4.0")
        call check(table%n_points_n == n_blocks_ref(), "Should have 50 density points")
        call check(table%n_points_m == n_mag_ref(), "Should have 101 magnetization points")
        call check(allocated(table%n_grid), "n_grid should be allocated")
        call check(allocated(table%m_grid), "m_grid should be allocated")
        call check(allocated(table%exc), "exc should be allocated")
        call check(allocated(table%vxc_up), "vxc_up should be allocated")
        call check(allocated(table%vxc_down), "vxc_down should be allocated")
        if (check_failed()) then
            call deallocate_table(table)
            call remove_file(fname)
            return
        end if

        ! The parsed values must reproduce what was written
        call check(abs(table%n_grid(1) - n_ref(1)) < 1.0e-10_dp, &
                   "First density should round-trip through the ASCII parser")
        call check(abs(table%n_grid(n_blocks_ref()) - n_ref(n_blocks_ref())) < 1.0e-10_dp, &
                   "Last density should round-trip through the ASCII parser")
        call check(abs(table%exc(7, 13) - exc_ref(7, 13)) < 1.0e-10_dp, &
                   "exc should be parsed into the (mag, density) slot it was written to")
        call check(abs(table%vxc_down(7, 13) - vxc_down_ref(7, 13)) < 1.0e-10_dp, &
                   "vxc_down should be parsed into the correct column")

        call deallocate_table(table)
        call remove_file(fname)
    end subroutine test_read_cpp_u4


    subroutine test_extract_u_standard()
        use fortuno_serial, only: check => serial_check
        use table_io, only: extract_U_from_filename
        use lsda_constants, only: dp

        real(dp) :: U
        integer :: status

        call extract_U_from_filename("build/test_tmp/lsda_hub_u4.00", U, status)

        call check(status == 0, "Should extract U from standard filename")
        call check(abs(U - 4.0_dp) < 1.0e-10_dp, "U should be 4.0")
    end subroutine test_extract_u_standard


    subroutine test_extract_u_binary()
        use fortuno_serial, only: check => serial_check
        use table_io, only: extract_U_from_filename
        use lsda_constants, only: dp

        real(dp) :: U
        integer :: status

        call extract_U_from_filename("xc_table_u10.00.dat", U, status)

        call check(status == 0, "Should extract U from binary filename")
        call check(abs(U - 10.0_dp) < 1.0e-10_dp, "U should be 10.0")
    end subroutine test_extract_u_binary


    subroutine test_extract_u_invalid()
        use fortuno_serial, only: check => serial_check
        use table_io, only: extract_U_from_filename
        use lsda_constants, only: dp

        real(dp) :: U
        integer :: status

        call extract_U_from_filename("invalid_filename.dat", U, status)

        call check(status /= 0, "Should fail for invalid filename")
    end subroutine test_extract_u_invalid


    !> The name the generator writes must be the name the SCF looks up.
    !!
    !! Regression test for the `|U| < 1` divergence: the generator formatted the
    !! magnitude with a bare `F0.2`, which gfortran prints without the leading
    !! zero, so it wrote `xc_table_u.50.dat` while the run-time lookup asked for
    !! `xc_table_u0.50.dat` and never found it - for the whole `0.5 <= |U| < 1`
    !! range.  Both sides now call `xc_table_filename`, so the check is that the
    !! shared name carries the zero and survives `extract_U_from_filename`.
    subroutine test_table_filename_roundtrip()
        use fortuno_serial, only: check => serial_check
        use table_io, only: xc_table_filename, extract_U_from_filename
        use lsda_constants, only: dp

        real(dp), parameter :: U_VALUES(5) = &
            [0.50_dp, 0.75_dp, -0.50_dp, 1.00_dp, 10.00_dp]
        character(len=256) :: path
        real(dp) :: U_back
        integer :: i, status

        do i = 1, size(U_VALUES)
            call xc_table_filename('tables', U_VALUES(i), path)
            call check(index(path, 'xc_table_u.') == 0, &
                       "the table name must never drop the leading zero of |U| < 1")
            call extract_U_from_filename(trim(path), U_back, status)
            call check(status == 0, "the generated table name must be parseable")
            call check(abs(U_back - abs(U_VALUES(i))) < 1.0e-10_dp, &
                       "the table name must round-trip to |U|")
        end do

        call xc_table_filename('tables', 0.5_dp, path)
        call check(trim(path) == 'tables/xc_table_u0.50.dat', &
                   "U = 0.5 must map to xc_table_u0.50.dat")
        call xc_table_filename('dir/', 0.5_dp, path)
        call check(trim(path) == 'dir/xc_table_u0.50.dat', &
                   "a trailing slash must not be doubled")
        call xc_table_filename('', 4.0_dp, path)
        call check(trim(path) == 'xc_table_u4.00.dat', &
                   "an empty directory must give a bare file name")
    end subroutine test_table_filename_roundtrip


    subroutine test_binary_roundtrip()
        use fortuno_serial, only: check => serial_check
        use table_io
        use lsda_constants, only: dp

        type(xc_table_t) :: table_in, table_out
        integer :: status
        logical :: ok
        character(len=*), parameter :: src_file = "build/test_tmp/roundtrip_hub_u4.00"
        character(len=*), parameter :: bin_file = "build/test_tmp/roundtrip_table_u4.00.dat"

        call make_cpp_table_file(src_file, ok)
        call check(ok, "Fixture table should be written")
        if (check_failed()) then
            call remove_file(src_file)
            call remove_file(bin_file)
            return
        end if

        call read_cpp_table(src_file, table_in, status)
        call check(status == 0, "Should read C++ table")
        call check(table_is_allocated(table_in), "C++ table arrays should be allocated")
        if (check_failed()) then
            call deallocate_table(table_in)
            call remove_file(src_file)
            call remove_file(bin_file)
            return
        end if

        call write_fortran_table(bin_file, table_in, status)
        call check(status == 0, "Should write binary table")
        if (check_failed()) then
            call deallocate_table(table_in)
            call remove_file(src_file)
            call remove_file(bin_file)
            return
        end if

        call read_fortran_table(bin_file, table_out, status)
        call check(status == 0, "Should read binary table")
        call check(table_is_allocated(table_out), "Binary table arrays should be allocated")
        if (check_failed()) then
            call deallocate_table(table_in)
            call deallocate_table(table_out)
            call remove_file(src_file)
            call remove_file(bin_file)
            return
        end if

        call check(abs(table_in%U - table_out%U) < 1.0e-14_dp, &
                   "U should match after round-trip")
        call check(table_in%n_points_n == table_out%n_points_n, &
                   "n_points_n should match")
        call check(table_in%n_points_m == table_out%n_points_m, &
                   "n_points_m should match")

        ! The binary format is unformatted stream, so the round-trip must hold
        ! over the WHOLE arrays, not just at a couple of sampled indices.
        call check(maxval(abs(table_in%n_grid - table_out%n_grid)) < 1.0e-14_dp, &
                   "n_grid should survive the round-trip to 1e-14")
        call check(maxval(abs(table_in%m_grid - table_out%m_grid)) < 1.0e-14_dp, &
                   "m_grid should survive the round-trip to 1e-14")
        call check(maxval(abs(table_in%exc - table_out%exc)) < 1.0e-14_dp, &
                   "exc should survive the round-trip to 1e-14")
        call check(maxval(abs(table_in%vxc_up - table_out%vxc_up)) < 1.0e-14_dp, &
                   "vxc_up should survive the round-trip to 1e-14")
        call check(maxval(abs(table_in%vxc_down - table_out%vxc_down)) < 1.0e-14_dp, &
                   "vxc_down should survive the round-trip to 1e-14")

        call deallocate_table(table_in)
        call deallocate_table(table_out)
        call remove_file(src_file)
        call remove_file(bin_file)
    end subroutine test_binary_roundtrip


    subroutine test_table_dimensions()
        use fortuno_serial, only: check => serial_check
        use table_io

        type(xc_table_t) :: table
        integer :: status
        logical :: ok
        character(len=*), parameter :: fname = "build/test_tmp/dims_hub_u4.00"

        call make_cpp_table_file(fname, ok)
        call check(ok, "Fixture table should be written")
        if (check_failed()) then
            call remove_file(fname)
            return
        end if

        call read_cpp_table(fname, table, status)
        call check(status == 0, "Should read table")
        call check(table_is_allocated(table), "Table arrays should be allocated")
        if (check_failed()) then
            call deallocate_table(table)
            call remove_file(fname)
            return
        end if

        call check(size(table%n_grid) == table%n_points_n, &
                   "n_grid size should match n_points_n")
        call check(size(table%m_grid, 1) == table%n_points_m, &
                   "m_grid first dimension should match n_points_m")
        call check(size(table%m_grid, 2) == table%n_points_n, &
                   "m_grid second dimension should match n_points_n")
        call check(size(table%exc, 1) == table%n_points_m, &
                   "exc first dimension should match n_points_m")
        call check(size(table%exc, 2) == table%n_points_n, &
                   "exc second dimension should match n_points_n")
        call check(size(table%vxc_up, 1) == table%n_points_m .and. &
                   size(table%vxc_up, 2) == table%n_points_n, &
                   "vxc_up dimensions should match the table size")
        call check(size(table%vxc_down, 1) == table%n_points_m .and. &
                   size(table%vxc_down, 2) == table%n_points_n, &
                   "vxc_down dimensions should match the table size")

        call deallocate_table(table)
        call remove_file(fname)
    end subroutine test_table_dimensions


    subroutine test_table_ranges()
        use fortuno_serial, only: check => serial_check
        use table_io
        use lsda_constants, only: dp

        type(xc_table_t) :: table
        integer :: status
        logical :: ok
        real(dp) :: n_min, n_max, m_min, m_max
        character(len=*), parameter :: fname = "build/test_tmp/ranges_hub_u4.00"

        call make_cpp_table_file(fname, ok)
        call check(ok, "Fixture table should be written")
        if (check_failed()) then
            call remove_file(fname)
            return
        end if

        call read_cpp_table(fname, table, status)
        call check(status == 0, "Should read table")
        call check(table_is_allocated(table), "Table arrays should be allocated")
        if (check_failed()) then
            call deallocate_table(table)
            call remove_file(fname)
            return
        end if

        n_min = minval(table%n_grid)
        n_max = maxval(table%n_grid)

        call check(n_min > 0.0_dp, "Minimum density should be positive")
        call check(n_max <= 1.0_dp + 1.0e-6_dp, "Maximum density should be <= 1")
        call check(n_min < n_max, "Density should be increasing")

        m_min = minval(table%m_grid)
        m_max = maxval(table%m_grid)

        call check(m_min >= 0.0_dp - 1.0e-10_dp, "Minimum magnetization should be >= 0")
        call check(m_max <= n_max + 1.0e-6_dp, "Maximum magnetization should be <= n_max")

        call check(maxval(table%exc) <= 0.0_dp + 1.0e-10_dp, &
                   "XC energy should be negative or zero")

        call check(abs(table%vxc_up(1,1) - table%vxc_down(1,1)) < 1.0e-10_dp, &
                   "At m=0, vxc_up should equal vxc_down")

        call deallocate_table(table)
        call remove_file(fname)
    end subroutine test_table_ranges


    subroutine test_missing_file()
        use fortuno_serial, only: check => serial_check
        use table_io

        type(xc_table_t) :: table
        integer :: status

        call read_cpp_table("build/test_tmp/nonexistent_hub_u4.00", table, status)

        call check(status /= 0, "Should fail for missing file")
        call check(.not. allocated(table%n_grid), "Arrays should not be allocated on error")
        call check(.not. allocated(table%m_grid), "m_grid should not be allocated on error")
        call check(.not. allocated(table%exc), "exc should not be allocated on error")
    end subroutine test_missing_file


    !> A failed read must not leave a table that later writes can choke on
    !!
    !! Regression guard: when the source table is missing, read_cpp_table
    !! returns a non-zero status and an unallocated table. write_fortran_table
    !! must reject that table via its status instead of dereferencing the
    !! unallocated components, and read_fortran_table must report the missing
    !! output file rather than reading stale data.
    subroutine test_missing_file_roundtrip_is_safe()
        use fortuno_serial, only: check => serial_check
        use table_io

        type(xc_table_t) :: table_in, table_out
        integer :: status
        character(len=*), parameter :: bin_file = "build/test_tmp/never_written_u4.00.dat"

        call ensure_scratch_dir()
        call remove_file(bin_file)

        call read_cpp_table("build/test_tmp/nonexistent_hub_u4.00", table_in, status)
        call check(status /= 0, "Reading a missing source table should fail")
        call check(.not. allocated(table_in%n_grid), "Failed read should leave table unallocated")
        if (check_failed()) then
            call deallocate_table(table_in)
            call remove_file(bin_file)
            return
        end if

        call write_fortran_table(bin_file, table_in, status)
        call check(status /= 0, "Writing an unallocated table should fail, not crash")
        if (check_failed()) then
            call deallocate_table(table_in)
            call remove_file(bin_file)
            return
        end if

        call read_fortran_table(bin_file, table_out, status)
        call check(status /= 0, "Reading the never-written binary table should fail")
        call check(.not. allocated(table_out%n_grid), &
                   "Failed binary read should leave table unallocated")
    end subroutine test_missing_file_roundtrip_is_safe


    subroutine test_deallocate_table()
        use fortuno_serial, only: check => serial_check
        use table_io

        type(xc_table_t) :: table
        integer :: status
        logical :: ok
        character(len=*), parameter :: fname = "build/test_tmp/dealloc_hub_u4.00"

        call make_cpp_table_file(fname, ok)
        call check(ok, "Fixture table should be written")
        if (check_failed()) then
            call remove_file(fname)
            return
        end if

        call read_cpp_table(fname, table, status)
        call check(status == 0, "Should read table")
        call check(allocated(table%n_grid), "Arrays should be allocated")
        call check(table_is_allocated(table), "All table arrays should be allocated")
        if (check_failed()) then
            call deallocate_table(table)
            call remove_file(fname)
            return
        end if

        call deallocate_table(table)

        call check(.not. allocated(table%n_grid), "n_grid should be deallocated")
        call check(.not. allocated(table%m_grid), "m_grid should be deallocated")
        call check(.not. allocated(table%exc), "exc should be deallocated")
        call check(.not. allocated(table%vxc_up), "vxc_up should be deallocated")
        call check(.not. allocated(table%vxc_down), "vxc_down should be deallocated")

        ! Deallocating twice must be a no-op, not an error
        call deallocate_table(table)
        call check(.not. allocated(table%n_grid), "Second deallocate should stay deallocated")

        call remove_file(fname)
    end subroutine test_deallocate_table


    subroutine test_multiple_tables()
        use fortuno_serial, only: check => serial_check
        use table_io
        use lsda_constants, only: dp

        type(xc_table_t) :: table1, table2, table3
        integer :: status
        logical :: ok1, ok2, ok3
        character(len=*), parameter :: f1 = "build/test_tmp/multi_hub_u2.00"
        character(len=*), parameter :: f2 = "build/test_tmp/multi_hub_u4.00"
        character(len=*), parameter :: f3 = "build/test_tmp/multi_hub_u10.00"

        call make_cpp_table_file(f1, ok1)
        call make_cpp_table_file(f2, ok2)
        call make_cpp_table_file(f3, ok3)
        call check(ok1 .and. ok2 .and. ok3, "Fixture tables should be written")
        if (check_failed()) then
            call remove_file(f1)
            call remove_file(f2)
            call remove_file(f3)
            return
        end if

        call read_cpp_table(f1, table1, status)
        call check(status == 0, "Should read U=2 table")
        call check(table_is_allocated(table1), "U=2 table arrays should be allocated")
        if (check_failed()) then
            call deallocate_table(table1)
            call deallocate_table(table2)
            call deallocate_table(table3)
            call remove_file(f1)
            call remove_file(f2)
            call remove_file(f3)
            return
        end if

        call read_cpp_table(f2, table2, status)
        call check(status == 0, "Should read U=4 table")
        call check(table_is_allocated(table2), "U=4 table arrays should be allocated")
        if (check_failed()) then
            call deallocate_table(table1)
            call deallocate_table(table2)
            call deallocate_table(table3)
            call remove_file(f1)
            call remove_file(f2)
            call remove_file(f3)
            return
        end if

        call read_cpp_table(f3, table3, status)
        call check(status == 0, "Should read U=10 table")
        call check(table_is_allocated(table3), "U=10 table arrays should be allocated")
        if (check_failed()) then
            call deallocate_table(table1)
            call deallocate_table(table2)
            call deallocate_table(table3)
            call remove_file(f1)
            call remove_file(f2)
            call remove_file(f3)
            return
        end if

        ! Each table must carry the U encoded in its own filename: tables held
        ! simultaneously must not share state.
        call check(abs(table1%U - 2.0_dp) < 1.0e-10_dp, "table1 U should be 2.0")
        call check(abs(table2%U - 4.0_dp) < 1.0e-10_dp, "table2 U should be 4.0")
        call check(abs(table3%U - 10.0_dp) < 1.0e-10_dp, "table3 U should be 10.0")

        call check(table1%n_points_n == n_blocks_ref(), "table1 should have 50 density points")
        call check(table2%n_points_n == n_blocks_ref(), "table2 should have 50 density points")
        call check(table3%n_points_n == n_blocks_ref(), "table3 should have 50 density points")

        call check(table1%n_points_m == n_mag_ref(), "table1 should have 101 magnetization points")
        call check(table2%n_points_m == n_mag_ref(), "table2 should have 101 magnetization points")
        call check(table3%n_points_m == n_mag_ref(), "table3 should have 101 magnetization points")

        call deallocate_table(table1)
        call deallocate_table(table2)
        call deallocate_table(table3)
        call remove_file(f1)
        call remove_file(f2)
        call remove_file(f3)
    end subroutine test_multiple_tables

end program test_table_io
