build_hamiltonian – LSDA-Hubbard-Fortran
build_hamiltonian Subroutine
MIT
24 statements
Source File
public subroutine build_hamiltonian(L, V_ext, V_xc, bc_type, theta, H, ierr)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: L
real(kind=dp), intent(in) :: V_ext(:)
real(kind=dp), intent(in) :: V_xc(:)
integer, intent(in) :: bc_type
real(kind=dp), intent(in), optional :: theta
real(kind=dp), intent(out) :: H(:,:)
integer, intent(out) :: ierr
Calls
Called by
Source Code
    subroutine build_hamiltonian(L, V_ext, V_xc, bc_type, theta, H, ierr)
        integer, intent(in) :: L
        real(dp), intent(in) :: V_ext(:), V_xc(:)
        integer, intent(in) :: bc_type
        real(dp), intent(in), optional :: theta
        real(dp), intent(out) :: H(:,:)
        integer, intent(out) :: ierr
        integer :: i
        call validate_hamiltonian_inputs(L, V_ext, V_xc, ierr)
        if (ierr /= 0) return
        if (size(H, 1) /= L .or. size(H, 2) /= L) then
            ierr = ERROR_SIZE_MISMATCH
            return
        end if
        H = 0.0_dp
        do i = 1, L
            H(i,i) = V_ext(i) + V_xc(i)
        end do
        do i = 1, L - 1
            H(i,i+1) = -1.0_dp ! Assuming hopping parameter t = 1
            H(i+1,i) = -1.0_dp ! Assuming hopping parameter t = 1
        end do
        call apply_boundary_conditions(H, L, bc_type, theta, ierr)
    end subroutine build_hamiltonian
Call graph
build_hamiltonian calls apply_boundary_conditions, validate_hamiltonian_inputs
apply_boundary_conditions calls validate_bc_parameters
run_kohn_sham_scf_real calls build_hamiltonian