check_scf_convergence – LSDA-Hubbard-Fortran
check_scf_convergence Subroutine
MIT
23 statements
Source File
public subroutine check_scf_convergence(delta_n, L, tol, is_converged, ierr)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: delta_n(:)
integer, intent(in) :: L
real(kind=dp), intent(in), optional :: tol
logical, intent(out) :: is_converged
integer, intent(out) :: ierr
Calls
Called by
Source Code
    subroutine check_scf_convergence(delta_n, L, tol, is_converged, ierr)
        real(dp), intent(in) :: delta_n(:)
        integer, intent(in) :: L
        real(dp), intent(in), optional :: tol
        logical, intent(out) :: is_converged
        integer, intent(out) :: ierr
        real(dp) :: norm_value
        real(dp) :: tolerance
        integer :: norm_type
        norm_type = L2
        if (present(tol)) then
            tolerance = tol
        else
            tolerance = 1.0e-6_dp
        end if
        call compute_density_norm(delta_n, L, norm_type, norm_value, ierr)
        if (ierr /= ERROR_SUCCESS) then
            is_converged = .false.
            return
        end if
        ierr = ERROR_SUCCESS
        is_converged = (norm_value < tolerance)
    end subroutine check_scf_convergence
Call graph
check_scf_convergence calls compute_density_norm
run_kohn_sham_scf_complex calls check_scf_convergence
run_kohn_sham_scf_real calls check_scf_convergence