compute_residual – LSDA-Hubbard-Fortran
compute_residual Function
MIT
34 statements
Source File
public function compute_residual(k, Lambda, I, J_capital, L, U) result(F)
Computes the residual vector F(x) for the Lieb-Wu equations of the 1D Hubbard model.
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: k(:)
real(kind=dp), intent(in) :: Lambda(:)
real(kind=dp), intent(in) :: I(:)
real(kind=dp), intent(in) :: J_capital(:)
integer, intent(in) :: L
real(kind=dp), intent(in) :: U
Return Value real(kind=dp), (size(k)+size(Lambda))
Calls
Called by
Source Code
    function compute_residual(k, Lambda, I, J_capital, L, U) result(F)
        real(dp), intent(in) :: k(:), Lambda(:), I(:), J_capital(:), U
        integer, intent(in) :: L
        integer :: j, alpha, beta, Nup, M
        real(dp) :: summ, summ1, summ2
        real(dp) :: F(size(k) + size(Lambda))
        Nup = size(k)
        M = size(Lambda)
        ! Special case: U ≈ 0
        if (abs(U) < U_SMALL) then
            ! For U=0, the exact solution is k_j = 2π·I_j/L
            ! Residual must be exactly zero
            F(1:Nup) = k - TWOPI * I / real(L, dp)
            F(Nup+1:Nup+M) = 0.0_dp  ! Lambda is arbitrary
            return
        end if
        ! General case: U > 0
        ! Charge equations: F^k
        do j = 1, Nup
            summ = 0.0_dp
            do alpha = 1, M
                summ = summ + theta(k(j) - Lambda(alpha), U)
            end do
            F(j) = k(j) - (TWOPI * I(j))/L - summ/L
        end do
        ! Spin equations: F^Lambda
        do alpha = 1, M
            summ1 = 0.0_dp
            summ2 = 0.0_dp
            do j = 1, Nup
                summ1 = summ1 + theta(Lambda(alpha) - k(j), U)
            end do
            do beta = 1, M
                if (beta /= alpha) then
                    summ2 = summ2 + Theta_capital(Lambda(alpha) - Lambda(beta), U)
                end if
            end do
            F(Nup + alpha) = (TWOPI * J_capital(alpha))/L - summ1 + summ2
        end do
    end function compute_residual
Call graph
compute_residual calls theta, theta_capital
compute_e_xc calls compute_residual, solve_newton
line_search calls compute_residual
solve_newton calls compute_residual, line_search
compute_v_xc_numerical calls compute_e_xc
generate_xc_table calls compute_e_xc, compute_v_xc_numerical
sweep_u_backward calls solve_newton
sweep_u_forward calls solve_newton
generate_table_grid calls generate_xc_table
sweep_u_bidirectional calls sweep_u_backward, sweep_u_forward