compute_E_xc – LSDA-Hubbard-Fortran
compute_E_xc Function
MIT
41 statements
Source File
public function compute_E_xc(n_up, n_dn, U, L) result(E_xc)
Compute exchange-correlation energy: E_xc = E_BA - E_0
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: n_up
real(kind=dp), intent(in) :: n_dn
real(kind=dp), intent(in) :: U
integer, intent(in) :: L
Return Value real(kind=dp)
Calls
Called by
Source Code
    function compute_E_xc(n_up, n_dn, U, L) result(E_xc)
        real(dp), intent(in) :: n_up, n_dn, U
        integer, intent(in) :: L
        real(dp) :: E_xc
        integer :: Nup, Ndn, M
        real(dp) :: E0, E_BA
        real(dp), allocatable :: x(:), k(:), F(:)
        real(dp), allocatable :: quantum_I(:), quantum_J(:)
        logical :: converged
        if (abs(U) < U_SMALL) then
            E_xc = 0.0_dp
            return
        end if
        Nup = nint(n_up * real(L, dp))
        Ndn = nint(n_dn * real(L, dp))
        M = Ndn
        allocate(x(Nup + M))  ! Combined array for solver (k + Lambda)
        allocate(k(Nup))
        allocate(F(Nup + M))
        allocate(quantum_I(Nup), quantum_J(M))
        call initialize_quantum_numbers(Nup, M, quantum_I, quantum_J)
        x(1:Nup) = TWOPI * quantum_I / real(L, dp)
        if (M > 0) then
            x(Nup+1:Nup+M) = 0.0_dp
        end if
        call solve_newton(x, quantum_I, quantum_J, L, U, converged)
        if (.not. converged) then
            F = compute_residual(x(1:Nup), x(Nup+1:Nup+M), quantum_I, quantum_J, L, U)
            if (norm2(F) > 1.0e-8_dp) then
                E_xc = ieee_value(E_xc, ieee_quiet_nan)
                deallocate(x, k, quantum_I, quantum_J, F)
                return
            end if
            deallocate(F)
        end if
        k = x(1:Nup)
        E_BA = compute_energy(k)
        E0 = compute_E0(n_up, n_dn, L)
        E_xc = (E_BA - E0) / real(L, dp)
        deallocate(x, k, quantum_I, quantum_J)
    end function compute_E_xc
Call graph
compute_e_xc calls compute_e0, compute_energy, compute_residual, initialize_quantum_numbers, solve_newton
compute_residual calls theta, theta_capital
solve_newton calls compute_residual, compute_jacobian, line_search, solve_linear_system
line_search calls compute_residual
solve_linear_system calls dgesv
compute_v_xc_numerical calls compute_e_xc
generate_xc_table calls compute_e_xc, compute_v_xc_numerical
generate_table_grid calls generate_xc_table