compute_V_xc_numerical – LSDA-Hubbard-Fortran
compute_V_xc_numerical Function
MIT
24 statements
Source File
public function compute_V_xc_numerical(n_up, n_dw, U, L) result(v_xc)
Compute XC potentials via numerical derivatives (central finite differences)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: n_up
real(kind=dp), intent(in) :: n_dw
real(kind=dp), intent(in) :: U
integer, intent(in) :: L
Return Value type(xc_potentials_t)
Calls
Called by
Source Code
    function compute_V_xc_numerical(n_up, n_dw, U, L) result(v_xc)
        real(dp), intent(in) :: n_up, n_dw
        integer, intent(in) :: L
        real(dp), intent(in) :: U
        type(xc_potentials_t) :: v_xc
        real(dp) :: delta_n
        real(dp) :: E_xc_up_plus, E_xc_up_minus
        real(dp) :: E_xc_dw_plus, E_xc_dw_minus
        delta_n = 1.0e-4_dp
        ! Derivative with respect to n_up
        E_xc_up_plus = compute_E_xc(n_up + delta_n, n_dw, U, L)
        E_xc_up_minus = compute_E_xc(n_up - delta_n, n_dw, U, L)
        if (ieee_is_nan(E_xc_up_plus) .or. ieee_is_nan(E_xc_up_minus)) then
            v_xc%v_xc_up = ieee_value(0.0_dp, ieee_quiet_nan)
        else
            v_xc%v_xc_up = (E_xc_up_plus - E_xc_up_minus) / (2.0_dp * delta_n)
        end if
        ! Derivative with respect to n_dw
        E_xc_dw_plus = compute_E_xc(n_up, n_dw + delta_n, U, L)
        E_xc_dw_minus = compute_E_xc(n_up, n_dw - delta_n, U, L)
        if (ieee_is_nan(E_xc_dw_plus) .or. ieee_is_nan(E_xc_dw_minus)) then
            v_xc%v_xc_down = ieee_value(0.0_dp, ieee_quiet_nan)
        else
            v_xc%v_xc_down = (E_xc_dw_plus - E_xc_dw_minus) / (2.0_dp * delta_n)
        end if
    end function compute_V_xc_numerical
Call graph
compute_v_xc_numerical calls compute_e_xc
compute_e_xc calls compute_e0, compute_energy, compute_residual, initialize_quantum_numbers, solve_newton
compute_residual calls theta, theta_capital
solve_newton calls compute_residual, compute_jacobian, line_search, solve_linear_system
line_search calls compute_residual
solve_linear_system calls dgesv
generate_xc_table calls compute_v_xc_numerical
generate_table_grid calls generate_xc_table