compute_total_energy – LSDA-Hubbard-Fortran
compute_total_energy Subroutine
MIT
35 statements
Source File
public subroutine compute_total_energy(eigvals_up, eigvals_down, n_up, n_down, density_up, density_down, V_ext, xc_func, U, L, total_energy, ierr)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: eigvals_up(:)
real(kind=dp), intent(in) :: eigvals_down(:)
integer, intent(in) :: n_up
integer, intent(in) :: n_down
real(kind=dp), intent(in) :: density_up(:)
real(kind=dp), intent(in) :: density_down(:)
real(kind=dp), intent(in) :: V_ext(:)
type(xc_lsda_t), intent(in) :: xc_func
real(kind=dp), intent(in) :: U
integer, intent(in) :: L
real(kind=dp), intent(out) :: total_energy
integer, intent(out) :: ierr
Calls
Called by
Source Code
    subroutine compute_total_energy(eigvals_up, eigvals_down, n_up, n_down, density_up, density_down, &
                                                            V_ext, xc_func, U, L, total_energy, ierr)
        real(dp), intent(in) :: eigvals_up(:), eigvals_down(:)
        integer, intent(in) :: n_up, n_down
        real(dp), intent(in) :: density_up(:), density_down(:), V_ext(:)
        type(xc_lsda_t), intent(in) :: xc_func
        real(dp), intent(in) :: U
        integer, intent(in) :: L
        real(dp), intent(out) :: total_energy
        integer, intent(out) :: ierr
        real(dp) :: E_band, E_hartree, E_xc_total, V_xc_correction
        real(dp) :: exc_val, V_xc_up, V_xc_down
        integer :: i
        ! 1. Band energy (sum of occupied eigenvalues)
        E_band = sum(eigvals_up(1:n_up)) + sum(eigvals_down(1:n_down))
        ! 2. Hartree energy: -U*Σ(n_up*n_down)
        !    Double-counting correction (matches C++ lsdaks.cc lines 676-679)
        !    Derivation: eigenvalues include V_eff = V_ext + U*n_other + V_xc
        !    When we sum v_eff*n for both spins, we get 2*U*n_up*n_down
        !    But we only want U*n_up*n_down, so we SUBTRACT U*n_up*n_down
        E_hartree = 0.0_dp
        do i = 1, L
            E_hartree = E_hartree + density_up(i) * density_down(i)
        end do
        E_hartree = -U * E_hartree  ! Negative sign!
        ! 3. Exchange-correlation energy and potential correction
        E_xc_total = 0.0_dp
        V_xc_correction = 0.0_dp
        do i = 1, L
            call get_exc(xc_func, density_up(i), density_down(i), exc_val, ierr)
            if (ierr /= ERROR_SUCCESS) then
                return
            end if
            call get_vxc(xc_func, density_up(i), density_down(i), &
                        V_xc_up, V_xc_down, ierr)
            if (ierr /= ERROR_SUCCESS) then
                return
            end if
            ! Note: exc_val is already the total XC energy at site i, not per particle!
            ! C++ just adds exc[i], not exc[i]*n_total[i]
            E_xc_total = E_xc_total + exc_val
            ! V_xc correction for double-counting
            V_xc_correction = V_xc_correction + V_xc_up * density_up(i) + V_xc_down * density_down(i)
        end do
        ! Total: E_band + E_hartree + E_xc - V_xc (matches C++ lsdaks.cc line 676-679)
        total_energy = E_band + E_hartree + E_xc_total - V_xc_correction
        ierr = ERROR_SUCCESS
    end subroutine compute_total_energy
Call graph
compute_total_energy calls get_exc, get_vxc
get_exc calls apply_symmetry_transform, convert_to_nm, determine_region, spline2d_eval
get_vxc calls apply_symmetry_transform, convert_to_nm, determine_region, spline2d_eval
spline2d_eval calls d2y_tmp, f_tmp, find_interval, spline1d_eval, y_tmp
spline1d_eval calls find_interval
run_kohn_sham_scf_complex calls compute_total_energy
run_kohn_sham_scf_real calls compute_total_energy