compute_E0 – LSDA-Hubbard-Fortran
compute_E0 Function
MIT
19 statements
Source File
public function compute_E0(n_up, n_dw, L) result(E0)
Compute non-interacting energy (U=0, free Fermi gas)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: n_up
real(kind=dp), intent(in) :: n_dw
integer, intent(in) :: L
Return Value real(kind=dp)
Called by
Source Code
    function compute_E0(n_up, n_dw, L) result(E0)
        real(dp), intent(in) :: n_up, n_dw
        integer, intent(in) :: L
        real(dp) :: E0, I_j, k_j
        integer :: Nup, Ndw, j
        Nup = NINT(n_up * real(L, dp))
        Ndw = NINT(n_dw * real(L, dp))
        E0 = 0.0_dp
        do j = 1, Nup
            I_j = real(j, dp) -0.5_dp * real(Nup + 1, dp)
            k_j = TWOPI * I_j / real(L, dp)
            E0 = E0 - 2.0_dp * cos(k_j)
        end do
        do j = 1, Ndw
            I_j = real(j, dp) -0.5_dp * real(Ndw + 1, dp)
            k_j = TWOPI * I_j / real(L, dp)
            E0 = E0 - 2.0_dp * cos(k_j)
        end do
    end function compute_E0
Call graph
compute_e_xc calls compute_e0
compute_v_xc_numerical calls compute_e_xc
generate_xc_table calls compute_e_xc, compute_v_xc_numerical
generate_table_grid calls generate_xc_table