create_potential – LSDA-Hubbard-Fortran
create_potential Subroutine
MIT
61 statements
Source File
public subroutine create_potential(potential_type, params, L, seed, V, ierr)
Factory function to create any potential type
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: potential_type
real(kind=dp), intent(in) :: params(:)
integer, intent(in) :: L
integer, intent(in) :: seed
real(kind=dp), intent(out), dimension(L) :: V
integer, intent(out) :: ierr
Calls
Source Code
    subroutine create_potential(potential_type, params, L, seed, V, ierr)
        character(len=*), intent(in) :: potential_type
        real(dp), intent(in) :: params(:)
        integer, intent(in) :: L, seed
        real(dp), dimension(L), intent(out) :: V
        integer, intent(out) :: ierr
        ! Initialize
        V = 0.0_dp
        ierr = ERROR_SUCCESS
        ! Select potential type
        select case (trim(adjustl(potential_type)))
        case ("uniform")
            ! Uniform potential: params(1) = V0
            if (size(params) < 1) then
                ierr = ERROR_INVALID_INPUT
                return
            end if
            call apply_potential_uniform(params(1), L, V, ierr)
        case ("harmonic")
            ! Harmonic trap: params(1) = k
            if (size(params) < 1) then
                ierr = ERROR_INVALID_INPUT
                return
            end if
            call apply_potential_harmonic(params(1), L, V, ierr)
        case ("impurity_single")
            ! Single impurity: params(1) = V_imp, params(2) = i_imp
            if (size(params) < 2) then
                ierr = ERROR_INVALID_INPUT
                return
            end if
            call potential_impurity_single(params(1), int(params(2)), L, V, ierr)
        case ("random_uniform")
            ! Random uniform: params(1) = W
            if (size(params) < 1) then
                ierr = ERROR_INVALID_INPUT
                return
            end if
            call potential_random_uniform(params(1), L, seed, V, ierr)
        case ("random_gaussian")
            ! Random Gaussian: params(1) = sigma
            if (size(params) < 1) then
                ierr = ERROR_INVALID_INPUT
                return
            end if
            call potential_random_gaussian(params(1), L, seed, V, ierr)
        case ("barrier_single")
            ! Single barrier: params(1) = V_bar, params(2) = i_start, params(3) = i_end
            if (size(params) < 3) then
                ierr = ERROR_INVALID_INPUT
                return
            end if
            call potential_barrier_single(params(1), int(params(2)), int(params(3)), L, V, ierr)
        case ("barrier_double")
            ! Double barrier: params(1) = V_bar, params(2) = L_bar, params(3) = V_well, params(4) = L_well
            ! Matches C++ double_barrier(Na, Vb, Lb, Vwell, Lwell, v_ext)
            if (size(params) < 4) then
                ierr = ERROR_INVALID_INPUT
                return
            end if
            call potential_barrier_double(params(1), params(2), params(3), params(4), L, V, ierr)
        case ("quasiperiodic")
            ! Quasiperiodic: params(1) = lambda, params(2) = beta, params(3) = phi
            if (size(params) < 3) then
                ierr = ERROR_INVALID_INPUT
                return
            end if
            call apply_potential_quasiperiodic(params(1), params(2), params(3), L, V, ierr)
        case default
            ierr = ERROR_INVALID_INPUT
        end select
    end subroutine create_potential
Call graph
create_potential calls apply_potential_harmonic, apply_potential_quasiperiodic, apply_potential_uniform, potential_barrier_double, potential_barrier_single, potential_impurity_single, potential_random_gaussian, potential_random_uniform