determine_region – LSDA-Hubbard-Fortran
determine_region Function
MIT
17 statements
Source File
private function determine_region(n_up, n_dw) result(region)
Determine symmetry region for (n_up, n_dw)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: n_up
real(kind=dp), intent(in) :: n_dw
Return Value integer
Called by
Source Code
    function determine_region(n_up, n_dw) result(region)
        real(dp), intent(in) :: n_up, n_dw
        integer :: region
        real(dp) :: n, m
        real(dp), parameter :: TOL = 1.0e-12_dp  ! Tolerance for boundary cases
        n = n_up + n_dw
        m = n_up - n_dw
        ! Use tolerances to handle floating-point errors at n = 1.0 boundary
        ! This is critical for half-filling cases where n = n_up + n_down = 1.0
        if (m >= -TOL .and. n <= 1.0_dp + TOL) then
            region = 1
        else if (m < -TOL .and. n <= 1.0_dp + TOL) then
            region = 2
        else if (m < -TOL .and. n > 1.0_dp + TOL) then
            region = 3
        else
            region = 4  ! m ≥ 0 and n > 1
        end if
    end function determine_region
Call graph
get_exc calls determine_region
get_vxc calls determine_region
compute_total_energy calls get_exc, get_vxc
run_kohn_sham_scf_complex calls get_vxc, compute_total_energy
run_kohn_sham_scf_real calls get_vxc, compute_total_energy