diagonalize_symmetric_real – LSDA-Hubbard-Fortran
diagonalize_symmetric_real Subroutine
MIT
38 statements
Source File
public subroutine diagonalize_symmetric_real(H, L, eigvals, eigvecs, ierr)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: H(:,:)
integer, intent(in) :: L
real(kind=dp), intent(out) :: eigvals(:)
real(kind=dp), intent(out) :: eigvecs(:,:)
integer, intent(out) :: ierr
Calls
Called by
Source Code
    subroutine diagonalize_symmetric_real(H, L, eigvals, eigvecs, ierr)
        real(dp), intent(in) :: H(:,:)
        integer, intent(in) :: L
        real(dp), intent(out) :: eigvals(:)
        real(dp), intent(out) :: eigvecs(:,:)
        integer, intent(out) :: ierr
        real(dp), allocatable :: H_work(:,:)
        real(dp), allocatable :: work(:)
        integer, allocatable :: iwork(:)
        integer :: lwork, liwork, info
        call validate_diagonalization_inputs(L, H, eigvals, eigvecs, .true., ierr)
        if (ierr /= ERROR_SUCCESS) return
        allocate(H_work(L,L))
        H_work = H
        lwork = -1
        liwork = -1
        allocate(work(1), iwork(1))
        call DSYEVD('V', 'U', L, H_work, L, eigvals, work, &
                lwork, iwork, liwork, info)
        if (info /= 0) then
            ierr = ERROR_LAPACK_INVALID_ARG
            deallocate(H_work, work, iwork)
            return
        end if
        lwork = int(work(1))
        liwork = iwork(1)
        deallocate(work, iwork)
        allocate(work(lwork), iwork(liwork))
        ! Actual diagonalization
        call DSYEVD('V', 'U', L, H_work, L, eigvals, work, &
                lwork, iwork, liwork, info)
        if (info < 0) then
            ierr = ERROR_LAPACK_INVALID_ARG
        else if (info > 0) then
            ierr = ERROR_CONVERGENCE_FAILED
        else
            ierr = ERROR_SUCCESS
            eigvecs = H_work
        end if
        deallocate(H_work, work, iwork)
    end subroutine diagonalize_symmetric_real
Call graph
diagonalize_symmetric_real calls dsyevd, validate_diagonalization_inputs
run_kohn_sham_scf_real calls diagonalize_symmetric_real