find_interval – LSDA-Hubbard-Fortran
find_interval Function
MIT
24 statements
Source File
private function find_interval(x_grid, n, x) result(i)
Find interval containing x in monotonic array
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: x_grid(0:)
integer, intent(in) :: n
real(kind=dp), intent(in) :: x
Return Value integer
Called by
Source Code
    function find_interval(x_grid, n, x) result(i)
        real(dp), intent(in) :: x_grid(0:), x
        integer, intent(in) :: n
        integer :: left, right, mid, i
        if (x <= x_grid(0)) then
            i = 0
            return
        end if
        if (x >= x_grid(n-1)) then
            i = n - 2
            return
        end if
        left = 0
        right = n - 1
        do while (right - left > 1)
            mid = (left + right) / 2
            if (x < x_grid(mid)) then
                right = mid
            else
                left = mid
            end if
        end do
        i = left
    end function find_interval
Call graph
spline1d_eval calls find_interval
spline2d_eval calls find_interval, spline1d_eval
get_exc calls spline2d_eval
get_vxc calls spline2d_eval
compute_total_energy calls get_exc, get_vxc
run_kohn_sham_scf_complex calls get_vxc, compute_total_energy
run_kohn_sham_scf_real calls get_vxc, compute_total_energy