generate_xc_table – LSDA-Hubbard-Fortran
generate_xc_table Subroutine
MIT
46 statements
Source File
public subroutine generate_xc_table(U, params, table, status)
Generate complete XC table for a single U value
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: U
type(grid_params_t), intent(in) :: params
type(xc_table_t), intent(out) :: table
integer, intent(out) :: status
Calls
Called by
Source Code
    subroutine generate_xc_table(U, params, table, status)
        real(dp), intent(in) :: U
        type(grid_params_t), intent(in) :: params
        type(xc_table_t), intent(out) :: table
        integer, intent(out) :: status
        integer :: i, j
        real(dp) :: n, m, n_up, n_dw, delta_n, delta_m
        type(xc_potentials_t) :: v_xc
        integer :: actual_m_points
        status = 0
        table%U = U
        table%n_points_n = params%n_points
        table%n_points_m = params%m_points
        allocate(table%n_grid(params%n_points))
        allocate(table%m_grid(params%m_points, params%n_points))
        allocate(table%exc(params%m_points, params%n_points))
        allocate(table%vxc_up(params%m_points, params%n_points))
        allocate(table%vxc_down(params%m_points, params%n_points))
        ! Initialize with NaN (for debugging)
        table%exc = ieee_value(0.0_dp, ieee_quiet_nan)
        table%vxc_up = ieee_value(0.0_dp, ieee_quiet_nan)
        table%vxc_down = ieee_value(0.0_dp, ieee_quiet_nan)
        delta_n = (params%n_max - params%n_min) / real(params%n_points - 1, dp)
        !$OMP PARALLEL DO PRIVATE(i, j, n, m, n_up, n_dw, delta_m, v_xc, actual_m_points) &
        !$OMP SHARED(table, params, U, delta_n) SCHEDULE(dynamic)
        do i = 1, params%n_points
            n = params%n_min + real(i - 1, dp) * delta_n
            table%n_grid(i) = n
            actual_m_points = params%m_points
            if (actual_m_points > 1) then
                delta_m = (2.0_dp * n) / real(actual_m_points - 1, dp)
            else
                delta_m = 0.0_dp
            end if
            do j = 1, actual_m_points
                m = -n + real(j - 1, dp) * delta_m
                table%m_grid(j, i) = m
                n_up = 0.5_dp * (n + m)
                n_dw = 0.5_dp * (n - m)
                if (n_up < 0.0_dp .or. n_up > 1.0_dp .or. &
                    n_dw < 0.0_dp .or. n_dw > 1.0_dp) then
                    cycle
                end if
                table%exc(j, i) = compute_E_xc(n_up, n_dw, U, params%L)
                v_xc = compute_V_xc_numerical(n_up, n_dw, U, params%L)
                table%vxc_up(j, i) = v_xc%v_xc_up
                table%vxc_down(j, i) = v_xc%v_xc_down
            end do
        end do
        !$OMP END PARALLEL DO
    end subroutine generate_xc_table
Call graph
generate_xc_table calls compute_e_xc, compute_v_xc_numerical
compute_e_xc calls compute_e0, compute_energy, compute_residual, initialize_quantum_numbers, solve_newton
compute_v_xc_numerical calls compute_e_xc
compute_residual calls theta, theta_capital
solve_newton calls compute_residual, compute_jacobian, line_search, solve_linear_system
line_search calls compute_residual
solve_linear_system calls dgesv
generate_table_grid calls generate_xc_table