generate_table_grid – LSDA-Hubbard-Fortran
generate_table_grid Subroutine
MIT
48 statements
Source File
public subroutine generate_table_grid(U_values, params, output_dir, status)
Generate multiple XC tables using continuation method in U
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: U_values(:)
type(grid_params_t), intent(in) :: params
character(len=*), intent(in) :: output_dir
integer, intent(out) :: status
Calls
Source Code
    subroutine generate_table_grid(U_values, params, output_dir, status)
        real(dp), intent(in) :: U_values(:)
        type(grid_params_t), intent(in) :: params
        character(len=*), intent(in) :: output_dir
        integer, intent(out) :: status
        integer :: k, n_U, io_stat
        real(dp) :: U_current
        type(xc_table_t) :: table
        character(len=256) :: filename
        character(len=32) :: U_str
        status = 0
        n_U = size(U_values)
        print '(A)', "========================================="
        print '(A)', "  XC Table Grid Generation"
        print '(A)', "========================================="
        print '(A,I0,A)', "Generating ", n_U, " tables with continuation method"
        print '(A,F6.2,A,F6.2)', "U range: ", U_values(1), " to ", U_values(n_U)
        print '(A,I0,A,I0)', "Grid size: ", params%n_points, " x ", params%m_points
        print '(A)', ""
        do k = 1, n_U
            U_current = U_values(k)
            print '(A,I0,A,I0,A,F6.2)', "Processing U(", k, "/", n_U, ") = ", U_current
            call generate_xc_table(U_current, params, table, status)
            if (status /= 0) then
                print '(A,F6.2)', "  ERROR: Failed to generate table for U = ", U_current
                return
            end if
            write(U_str, '(F6.2)') U_current
            U_str = adjustl(U_str)
            filename = trim(output_dir) // "/lsda_hub_u" // trim(U_str) // ".dat"
            call write_fortran_table(filename, table, io_stat)
            if (io_stat /= 0) then
                print '(A)', "  ERROR: Failed to write table file"
                status = -1
                return
            end if
            print '(A,A)', "  Saved: ", trim(filename)
            ! Deallocate table arrays for next iteration
            if (allocated(table%n_grid)) deallocate(table%n_grid)
            if (allocated(table%m_grid)) deallocate(table%m_grid)
            if (allocated(table%exc)) deallocate(table%exc)
            if (allocated(table%vxc_up)) deallocate(table%vxc_up)
            if (allocated(table%vxc_down)) deallocate(table%vxc_down)
        end do
        print '(A)', ""
        print '(A)', "========================================="
        print '(A,I0,A)', "Successfully generated ", n_U, " XC tables!"
        print '(A)', "========================================="
    end subroutine generate_table_grid
Call graph
generate_table_grid calls generate_xc_table, write_fortran_table
generate_xc_table calls compute_e_xc, compute_v_xc_numerical
compute_e_xc calls compute_e0, compute_energy, compute_residual, initialize_quantum_numbers, solve_newton
compute_v_xc_numerical calls compute_e_xc
compute_residual calls theta, theta_capital
solve_newton calls compute_residual, compute_jacobian, line_search, solve_linear_system
line_search calls compute_residual
solve_linear_system calls dgesv