get_exc – LSDA-Hubbard-Fortran
get_exc Subroutine
MIT
35 statements
Source File
public subroutine get_exc(xc, n_up, n_dw, exc, ierr)
Get exchange-correlation energy per particle at (n_up, n_dw)
Arguments
Type Intent Optional Attributes Name
type(xc_lsda_t), intent(in) :: xc
real(kind=dp), intent(in) :: n_up
real(kind=dp), intent(in) :: n_dw
real(kind=dp), intent(out) :: exc
integer, intent(out) :: ierr
Calls
Called by
Source Code
    subroutine get_exc(xc, n_up, n_dw, exc, ierr)
        type(xc_lsda_t), intent(in) :: xc
        real(dp), intent(in) :: n_up, n_dw
        real(dp), intent(out) :: exc
        integer, intent(out) :: ierr
        integer :: region
        real(dp) :: n_up_map, n_dw_map, n, m
        ! Check initialization
        if (.not. xc%initialized) then
            exc = 0.0_dp
            ierr = ERROR_INVALID_INPUT
            return
        end if
        ! Special case: U = 0 (free Fermi gas)
        if (abs(xc%U) < U_SMALL) then
            exc = 0.0_dp
            ierr = ERROR_SUCCESS
            return
        end if
        ! Check density bounds
        ! Note: Particle-hole symmetry allows n_up, n_down > 1.0
        ! Maximum total density is n_up + n_down ≤ 2 (Pauli exclusion)
        ! Use small tolerance to handle floating-point roundoff (e.g., 1.0+1.0 = 2.0000...009)
        if (n_up < -1.0e-12_dp .or. n_dw < -1.0e-12_dp .or. &
            (n_up + n_dw) > 2.0_dp + 1.0e-10_dp) then
            exc = 0.0_dp
            ierr = ERROR_OUT_OF_BOUNDS
            return
        end if
        ! Special case: both densities zero
        if (n_up < 1.0e-12_dp .and. n_dw < 1.0e-12_dp) then
            exc = 0.0_dp
            ierr = ERROR_SUCCESS
            return
        end if
        ! Determine region and apply symmetry
        region = determine_region(n_up, n_dw)
        call apply_symmetry_transform(region, n_up, n_dw, n_up_map, n_dw_map)
        ! Clip to valid range to handle numerical errors near boundaries
        ! This is especially important for n ≈ 2.0 where particle-hole transform
        ! can produce small negative values due to roundoff
        n_up_map = max(0.0_dp, min(1.0_dp, n_up_map))
        n_dw_map = max(0.0_dp, min(1.0_dp, n_dw_map))
        call convert_to_nm(n_up_map, n_dw_map, n, m)
        ! Evaluate spline
        exc = spline2d_eval(xc%spl_exc, n, m)
        ierr = ERROR_SUCCESS
    end subroutine get_exc
Call graph
get_exc calls apply_symmetry_transform, convert_to_nm, determine_region, spline2d_eval
spline2d_eval calls d2y_tmp, f_tmp, find_interval, spline1d_eval, y_tmp
spline1d_eval calls find_interval
compute_total_energy calls get_exc
run_kohn_sham_scf_complex calls compute_total_energy
run_kohn_sham_scf_real calls compute_total_energy