line_search – LSDA-Hubbard-Fortran
line_search Function
MIT
39 statements
Source File
public function line_search(x, dx, F_old, I, J, L, U) result(alpha)
Armijo backtracking line search for Newton-Raphson
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: x(:)
real(kind=dp), intent(in) :: dx(:)
real(kind=dp), intent(in) :: F_old(:)
real(kind=dp), intent(in) :: I(:)
real(kind=dp), intent(in) :: J(:)
integer, intent(in) :: L
real(kind=dp), intent(in) :: U
Return Value real(kind=dp)
Calls
Called by
Call graph
line_search calls compute_residual
compute_residual calls theta, theta_capital
solve_newton calls line_search
compute_e_xc calls solve_newton
sweep_u_backward calls solve_newton
sweep_u_forward calls solve_newton
compute_v_xc_numerical calls compute_e_xc
generate_xc_table calls compute_e_xc, compute_v_xc_numerical
sweep_u_bidirectional calls sweep_u_backward, sweep_u_forward
generate_table_grid calls generate_xc_table