parse_inputs – LSDA-Hubbard-Fortran
parse_inputs Subroutine
MIT
97 statements
Source File
public subroutine parse_inputs(inputs, ierr)
Parse inputs from command line or namelist file
Arguments
Type Intent Optional Attributes Name
type(input_params_t), intent(out) :: inputs
integer, intent(out) :: ierr
Calls
Source Code
    subroutine parse_inputs(inputs, ierr)
        type(input_params_t), intent(out) :: inputs
        integer, intent(out) :: ierr
        character(len=256) :: arg, input_file
        integer :: nargs, i
        logical :: use_input_file
        ierr = ERROR_SUCCESS
        use_input_file = .false.
        ! Initialize with defaults
        inputs = input_params_t()
        ! Check command line arguments
        nargs = command_argument_count()
        if (nargs == 0) then
            ! No arguments: try default input file
            input_file = 'input.txt'
            inquire(file=input_file, exist=use_input_file)
            if (.not. use_input_file) then
                print *, "WARNING: No input file or arguments provided."
                print *, "Using default parameters."
                return
            end if
        else
            ! Parse command line
            i = 1
            do while (i <= nargs)
                call get_command_argument(i, arg)
                select case (trim(arg))
                case ('--input', '-i')
                    if (i + 1 > nargs) then
                        print *, "ERROR: --input requires a filename"
                        ierr = ERROR_INVALID_INPUT
                        return
                    end if
                    call get_command_argument(i + 1, input_file)
                    use_input_file = .true.
                    i = i + 2
                case ('--L')
                    call parse_integer_arg(i, nargs, inputs%L, ierr)
                    if (ierr /= ERROR_SUCCESS) return
                    i = i + 2
                case ('--Nup')
                    call parse_integer_arg(i, nargs, inputs%Nup, ierr)
                    if (ierr /= ERROR_SUCCESS) return
                    i = i + 2
                case ('--Ndown')
                    call parse_integer_arg(i, nargs, inputs%Ndown, ierr)
                    if (ierr /= ERROR_SUCCESS) return
                    i = i + 2
                case ('--U')
                    call parse_real_arg(i, nargs, inputs%U, ierr)
                    if (ierr /= ERROR_SUCCESS) return
                    i = i + 2
                case ('--bc')
                    if (i + 1 > nargs) then
                        print *, "ERROR: --bc requires a value (open/periodic/twisted)"
                        ierr = ERROR_INVALID_INPUT
                        return
                    end if
                    call get_command_argument(i + 1, inputs%bc_type)
                    i = i + 2
                case ('--phase')
                    call parse_real_arg(i, nargs, inputs%phase, ierr)
                    if (ierr /= ERROR_SUCCESS) return
                    i = i + 2
                case ('--potential')
                    if (i + 1 > nargs) then
                        print *, "ERROR: --potential requires a type"
                        ierr = ERROR_INVALID_INPUT
                        return
                    end if
                    call get_command_argument(i + 1, inputs%potential_type)
                    i = i + 2
                case ('--V0')
                    call parse_real_arg(i, nargs, inputs%V0, ierr)
                    if (ierr /= ERROR_SUCCESS) return
                    i = i + 2
                case ('--concentration')
                    call parse_real_arg(i, nargs, inputs%concentration, ierr)
                    if (ierr /= ERROR_SUCCESS) return
                    i = i + 2
                case ('--verbose')
                    inputs%verbose = .true.
                    i = i + 1
                case ('--quiet')
                    inputs%verbose = .false.
                    i = i + 1
                case ('--help', '-h')
                    call print_help()
                    ierr = -1  ! Signal to exit gracefully
                    return
                case default
                    print *, "WARNING: Unknown argument: ", trim(arg)
                    i = i + 1
                end select
            end do
        end if
        ! Read namelist file if specified
        if (use_input_file) then
            call read_namelist_file(input_file, inputs, ierr)
            if (ierr /= ERROR_SUCCESS) return
        end if
    end subroutine parse_inputs
Call graph
parse_inputs calls parse_integer_arg, parse_real_arg, print_help, read_namelist_file