run_kohn_sham_scf_complex – LSDA-Hubbard-Fortran
run_kohn_sham_scf_complex Subroutine
MIT
178 statements
Source File
public subroutine run_kohn_sham_scf_complex(params, scf_params, V_ext, xc_func, results, ierr)
Arguments
Type Intent Optional Attributes Name
type(system_params_t), intent(in) :: params
type(scf_params_t), intent(in) :: scf_params
real(kind=dp), intent(in) :: V_ext(:)
type(xc_lsda_t), intent(in) :: xc_func
type(scf_results_t), intent(out) :: results
integer, intent(out) :: ierr
Calls
Source Code
    subroutine run_kohn_sham_scf_complex(params, scf_params, V_ext, xc_func, results, ierr)
        type(system_params_t), intent(in) :: params
        type(scf_params_t), intent(in) :: scf_params
        real(dp), intent(in) :: V_ext(:)
        type(xc_lsda_t), intent(in) :: xc_func
        type(scf_results_t), intent(out) :: results
        integer, intent(out) :: ierr
        integer :: iter, i, L, Nup, Ndown
        real(dp) :: density_error, total_energy
        logical :: is_converged
        type(adaptive_mix_t) :: mix_ctrl
        real(dp) :: current_alpha
        real(dp), allocatable :: n_up_in(:), n_down_in(:), n_up_out(:), n_down_out(:), V_xc_up(:), &
                      V_xc_down(:), eigvals_up(:), eigvals_down(:), delta_n_up(:), delta_n_down(:), &
                      delta_n_total(:), V_eff_up(:), V_eff_down(:), V_eff_up_calc(:), V_eff_down_calc(:), &
                      V_zero(:)
        complex(dp), allocatable :: H_up(:,:), H_down(:,:), eigvecs_up(:,:), eigvecs_down(:,:)
        call validate_kohn_sham_cycle_inputs(params, scf_params, V_ext, ierr)
        if (ierr /= ERROR_SUCCESS) then
            return
        end if
        L = params%L
        Nup = params%Nup
        Ndown = params%Ndown
        allocate(n_up_in(L), n_down_in(L), n_up_out(L), n_down_out(L), V_xc_up(L), V_xc_down(L), &
                 H_up(L,L), H_down(L,L), eigvals_up(L), eigvals_down(L), &
                 eigvecs_up(L,L), eigvecs_down(L,L), delta_n_up(L), delta_n_down(L), delta_n_total(L), &
                 V_eff_up(L), V_eff_down(L), V_eff_up_calc(L), V_eff_down_calc(L), V_zero(L))
        ! Initialize zero array for Hamiltonian builder
        V_zero(:) = 0.0_dp
        call init_convergence_history(results%history, scf_params%max_iter, ierr)
        if (ierr /= ERROR_SUCCESS) then
            ! TODO: Proper error handling for history init
            deallocate(n_up_in, n_down_in, n_up_out, n_down_out, V_xc_up, V_xc_down, &
                       H_up, H_down, eigvals_up, eigvals_down, eigvecs_up, eigvecs_down, delta_n_up, &
                       delta_n_down, delta_n_total, V_eff_up, V_eff_down, V_eff_up_calc, V_eff_down_calc, V_zero)
            return
        end if
        ! Initialize densities (uniform guess)
        n_up_in(:) = real(params%Nup, dp) / real(params%L, dp)
        n_down_in(:) = real(params%Ndown, dp) / real(params%L, dp)
        ! Initialize effective potentials from initial density guess
        ! This matches C++ initial_guess() function (lsdaks.cc lines 520-521)
        ! V_eff = V_ext + U*n_other + V_xc
        do i = 1, params%L
            ! Get V_xc from initial uniform density
            call get_vxc(xc_func, n_up_in(i), n_down_in(i), V_xc_up(i), V_xc_down(i), ierr)
            if (ierr /= ERROR_SUCCESS) then
                deallocate(n_up_in, n_down_in, n_up_out, n_down_out, V_xc_up, V_xc_down, &
                       H_up, H_down, eigvals_up, eigvals_down, eigvecs_up, eigvecs_down, delta_n_up, &
                       delta_n_down, delta_n_total, V_eff_up, V_eff_down, V_eff_up_calc, V_eff_down_calc, V_zero)
                return
            end if
            ! Initialize V_eff = V_ext + U*n_other + V_xc (like C++)
            V_eff_up(i) = V_ext(i) + params%U * n_down_in(i) + V_xc_up(i)
            V_eff_down(i) = V_ext(i) + params%U * n_up_in(i) + V_xc_down(i)
        end do
        ! =================================
        ! Initialize adaptive mixing (if enabled)
        ! =================================
        if (scf_params%use_adaptive_mixing) then
            call adaptive_mix_init(mix_ctrl, scf_params%energy_tol)
            if (scf_params%verbose) then
                print '(A)', "  Using adaptive mixing (C++ behavior)"
            end if
        else
            if (scf_params%verbose) then
                print '(A,F6.4)', "  Using fixed mixing alpha = ", scf_params%mixing_alpha
            end if
        end if
        ! =================
        ! STEP 1: SCF loop
        ! =================
        do iter = 1, scf_params%max_iter
            ! -------------------------------------------------
            ! 1a. Compute V_xc from current densities
            ! -------------------------------------------------
            do i = 1, params%L
                call get_vxc(xc_func, n_up_in(i), n_down_in(i), V_xc_up(i), V_xc_down(i), ierr)
                if (ierr /= ERROR_SUCCESS) then
                    ! TODO: Proper error handling for V_xc calculation
                    deallocate(n_up_in, n_down_in, n_up_out, n_down_out, V_xc_up, V_xc_down, &
                       H_up, H_down, eigvals_up, eigvals_down, eigvecs_up, eigvecs_down, delta_n_up, &
                       delta_n_down, delta_n_total, V_eff_up, V_eff_down, V_eff_up_calc, V_eff_down_calc, V_zero)
                    return
                end if
            end do
            ! -------------------------------------------------------------
            ! 1b. Calculate effective potentials V_eff = V_ext + U*n_other + V_xc
            ! (This is what C++ calls "v_ext[][j] + u*dens[other][j] + Vxc[][j]")
            ! -------------------------------------------------------------
            do i = 1, params%L
                ! V_eff_up_calc = V_ext + U*n_down + V_xc_up
                V_eff_up_calc(i) = V_ext(i) + params%U * n_down_in(i) + V_xc_up(i)
                ! V_eff_down_calc = V_ext + U*n_up + V_xc_down
                V_eff_down_calc(i) = V_ext(i) + params%U * n_up_in(i) + V_xc_down(i)
            end do
            ! -------------------------------------------------------------
            ! 1c. Mix potentials (C++ convention: Mix = weight of OLD)
            ! V_eff_new = Mix*V_eff_old + (1-Mix)*V_eff_calc
            ! -------------------------------------------------------------
            if (scf_params%use_adaptive_mixing) then
                ! Adaptive mixing uses the Mix parameter (updated each iteration)
                ! Convert to fortran alpha: alpha = 1 - Mix
                current_alpha = adaptive_mix_get_alpha(mix_ctrl)
                ! Apply mixing: V = (1-)*V_old + *V_calc = Mix*V_old + (1-Mix)*V_calc
                ! Since alpha = 1-Mix, we have: V = Mix*V_old + (1-Mix)*V_calc
                do i = 1, params%L
                    V_eff_up(i) = (1.0_dp - current_alpha) * V_eff_up(i) + current_alpha * V_eff_up_calc(i)
                    V_eff_down(i) = (1.0_dp - current_alpha) * V_eff_down(i) + current_alpha * V_eff_down_calc(i)
                end do
            else
                ! Fixed mixing: alpha = weight of new
                current_alpha = scf_params%mixing_alpha
                do i = 1, params%L
                    V_eff_up(i) = (1.0_dp - current_alpha) * V_eff_up(i) + current_alpha * V_eff_up_calc(i)
                    V_eff_down(i) = (1.0_dp - current_alpha) * V_eff_down(i) + current_alpha * V_eff_down_calc(i)
                end do
            end if
            ! -------------------------------------
            ! 1d. Build Hamiltonians with mixed V_eff
            ! (C++ passes v_eff to hamiltonian_ks)
            ! -------------------------------------
            call build_hamiltonian_complex(params%L, V_eff_up, V_zero, params%bc, params%phase, H_up, ierr)
            if (ierr /= ERROR_SUCCESS) then
                ! TODO: Proper error handling for Hamiltonian Nup build
                deallocate(n_up_in, n_down_in, n_up_out, n_down_out, V_xc_up, V_xc_down, &
                       H_up, H_down, eigvals_up, eigvals_down, eigvecs_up, eigvecs_down, delta_n_up, &
                       delta_n_down, delta_n_total, V_eff_up, V_eff_down, V_eff_up_calc, V_eff_down_calc, V_zero)
                return
            end if
            call build_hamiltonian_complex(params%L, V_eff_down, V_zero, params%bc, params%phase, H_down, ierr)
            if (ierr /= ERROR_SUCCESS) then
                ! TODO: Proper error handling for Hamiltonian Ndown build
                deallocate(n_up_in, n_down_in, n_up_out, n_down_out, V_xc_up, V_xc_down, &
                       H_up, H_down, eigvals_up, eigvals_down, eigvecs_up, eigvecs_down, delta_n_up, &
                       delta_n_down, delta_n_total, V_eff_up, V_eff_down, V_eff_up_calc, V_eff_down_calc, V_zero)
                return
            end if
            ! ---------------------------------
            ! 1d. Diagonalize both Hamiltonians
            ! ---------------------------------
            call diagonalize_hermitian_complex(H_up, params%L, eigvals_up, eigvecs_up, ierr)
            if (ierr /= ERROR_SUCCESS) then
                ! TODO: Proper error handling for diagonalization Nup Hamiltonian
                deallocate(n_up_in, n_down_in, n_up_out, n_down_out, V_xc_up, V_xc_down, &
                       H_up, H_down, eigvals_up, eigvals_down, eigvecs_up, eigvecs_down, delta_n_up, &
                       delta_n_down, delta_n_total)
                return
            end if
            call diagonalize_hermitian_complex(H_down, params%L, eigvals_down, eigvecs_down, ierr)
            if (ierr /= ERROR_SUCCESS) then
                ! TODO: Proper error handling for diagonalization Ndown Hamiltonian
                deallocate(n_up_in, n_down_in, n_up_out, n_down_out, V_xc_up, V_xc_down, &
                       H_up, H_down, eigvals_up, eigvals_down, eigvecs_up, eigvecs_down, delta_n_up, &
                       delta_n_down, delta_n_total)
                return
            end if
            ! ----------------------------------------------
            ! 1e. Compute new densities from eigenvectors
            ! ----------------------------------------------
            call compute_density_spin(eigvecs_up, params%L, params%Nup, n_up_out, ierr)
            if (ierr /= ERROR_SUCCESS) then
                ! TODO: Proper error handling for density calculation Nup
                deallocate(n_up_in, n_down_in, n_up_out, n_down_out, V_xc_up, V_xc_down, &
                       H_up, H_down, eigvals_up, eigvals_down, eigvecs_up, eigvecs_down, delta_n_up, &
                       delta_n_down, delta_n_total)
                return
            end if
            call compute_density_spin(eigvecs_down, params%L, params%Ndown, n_down_out, ierr)
            if (ierr /= ERROR_SUCCESS) then
                ! TODO: Proper error handling for density calculation Ndown
                deallocate(n_up_in, n_down_in, n_up_out, n_down_out, V_xc_up, V_xc_down, &
                       H_up, H_down, eigvals_up, eigvals_down, eigvecs_up, eigvecs_down, delta_n_up, &
                       delta_n_down, delta_n_total)
                return
            end if
            ! ----------------------------------------------
            ! 1f. Compute density differences
            ! ----------------------------------------------
            call compute_density_difference(n_up_out, n_up_in, params%L, delta_n_up, ierr)
            if (ierr /= ERROR_SUCCESS) then
                ! TODO: Proper error handling for Nup density difference
                deallocate(n_up_in, n_down_in, n_up_out, n_down_out, V_xc_up, V_xc_down, &
                       H_up, H_down, eigvals_up, eigvals_down, eigvecs_up, eigvecs_down, delta_n_up, &
                       delta_n_down, delta_n_total)
                return
            end if
            call compute_density_difference(n_down_out, n_down_in, params%L, delta_n_down, ierr)
            if (ierr /= ERROR_SUCCESS) then
                ! TODO: Proper error handling for Ndown density difference
                deallocate(n_up_in, n_down_in, n_up_out, n_down_out, V_xc_up, V_xc_down, &
                       H_up, H_down, eigvals_up, eigvals_down, eigvecs_up, eigvecs_down, delta_n_up, &
                       delta_n_down, delta_n_total)
                return
            end if
            ! ------------------------------
            ! 1g. Compute total density error
            ! ------------------------------
            delta_n_total = delta_n_up + delta_n_down
            call compute_density_norm(delta_n_total, params%L, L2, density_error, ierr)
            if (ierr /= ERROR_SUCCESS) then
                ! TODO: Proper error handling for total density up norm
                deallocate(n_up_in, n_down_in, n_up_out, n_down_out, V_xc_up, V_xc_down, &
                       H_up, H_down, eigvals_up, eigvals_down, eigvecs_up, eigvecs_down, delta_n_up, &
                       delta_n_down, delta_n_total)
                return
            end if
                ! ------------------------
            ! 1h. Compute total energy
            ! ------------------------
            call compute_total_energy(eigvals_up, eigvals_down, params%Nup, params%Ndown, n_up_out, n_down_out, &
                                    V_ext, xc_func, params%U, params%L, total_energy, ierr)
            if (ierr /= ERROR_SUCCESS) then
                ! TODO: Proper error handling for total energy calculation
                deallocate(n_up_in, n_down_in, n_up_out, n_down_out, V_xc_up, V_xc_down, &
                       H_up, H_down, eigvals_up, eigvals_down, eigvecs_up, eigvecs_down, delta_n_up, &
                       delta_n_down, delta_n_total)
                return
            end if
            ! ------------------
            ! 1i. Store history
            ! ------------------
            if (scf_params%store_history) then
                call update_convergence_history(iter, density_error, total_energy, results%history, ierr)
            end if
            if (ierr /= ERROR_SUCCESS) then
                ! TODO: Proper error handling for history update
                deallocate(n_up_in, n_down_in, n_up_out, n_down_out, V_xc_up, V_xc_down, &
                       H_up, H_down, eigvals_up, eigvals_down, eigvecs_up, eigvecs_down, delta_n_up, &
                       delta_n_down, delta_n_total)
                return
            end if
            ! ------------------------------
            ! 1j. Update adaptive mixing (if enabled)
            ! ------------------------------
            if (scf_params%use_adaptive_mixing) then
                call adaptive_mix_update(mix_ctrl, total_energy)
                current_alpha = adaptive_mix_get_alpha(mix_ctrl)
                if (scf_params%verbose) then
                    print '(A,I4,A,ES12.4,A,F16.8,A,F7.5)', "  Iter ", iter, "  |n| = ", density_error, &
                        "  E_tot = ", total_energy, "   = ", current_alpha
                end if
                ! Check convergence: density-based (primary) OR energy-based (fallback)
                ! With potential mixing, density converges even if energy oscillates slightly
                call check_scf_convergence(delta_n_total, params%L, scf_params%density_tol, &
                                           is_converged, ierr)
                if (ierr /= ERROR_SUCCESS .or. .not. is_converged) then
                    ! Density not converged OR error - fall back to energy-based check
                    is_converged = mix_ctrl%converged
                end if
            else
                current_alpha = scf_params%mixing_alpha
                if (scf_params%verbose) then
                    print '(A,I4,A,ES12.4,A,F16.8)', "  Iter ", iter, "  |n| = ", density_error, &
                                                                        "  E_tot = ", total_energy
                end if
                ! 1k. Check convergence (fixed mixing)
                call check_scf_convergence(delta_n_total, params%L, scf_params%density_tol, &
                                           is_converged, ierr)
            end if
            ! Validate convergence check
            if (.not. scf_params%use_adaptive_mixing .and. ierr /= ERROR_SUCCESS) then
                ! TODO: Proper error handling for convergence check
                deallocate(n_up_in, n_down_in, n_up_out, n_down_out, V_xc_up, V_xc_down, &
                       H_up, H_down, eigvals_up, eigvals_down, eigvecs_up, eigvecs_down, delta_n_up, &
                       delta_n_down, delta_n_total)
                return
            end if
            if (is_converged) then
                ! SUCCESS: Converged!
                results%converged = .true.
                results%n_iterations = iter
                results%final_density_error = density_error
                results%final_energy = total_energy
                ! Store final densities and eigenvalues
                allocate(results%density_up(params%L))
                allocate(results%density_down(params%L))
                allocate(results%eigvals(2*params%L))
                results%density_up = n_up_out
                results%density_down = n_down_out
                results%eigvals(1:params%L) = eigvals_up
                results%eigvals(params%L+1:2*params%L) = eigvals_down
                ierr = ERROR_SUCCESS
                return  ! return SCF LOOP
            end if
            ! -----------------------------------------------------------------------
            ! 1l. Copy densities directly (NO MIXING!)
            ! -----------------------------------------------------------------------
            ! C++ code does: dens[0][i] = next_dens[0][i]  (line 695-696 in lsdaks.cc)
            ! Mixing is applied to POTENTIALS, not densities!
            n_up_in = n_up_out
            n_down_in = n_down_out
        end do
        ! ========================
        ! STEP 2: Did not converge
        ! ========================
        results%converged = .false.
        results%n_iterations = scf_params%max_iter
        results%final_density_error = density_error
        results%final_energy = total_energy
        ierr = ERROR_CONVERGENCE_FAILED
        deallocate(n_up_in, n_down_in, n_up_out, n_down_out, V_xc_up, V_xc_down, &
                       H_up, H_down, eigvals_up, eigvals_down, eigvecs_up, eigvecs_down, delta_n_up, &
                       delta_n_down, delta_n_total)
    end subroutine run_kohn_sham_scf_complex
Call graph
run_kohn_sham_scf_complex calls compute_density_spin, adaptive_mix_get_alpha, adaptive_mix_init, adaptive_mix_update, build_hamiltonian_complex, check_scf_convergence, compute_density_difference, compute_density_norm, compute_total_energy, diagonalize_hermitian_complex, get_vxc, init_convergence_history, update_convergence_history, validate_kohn_sham_cycle_inputs
compute_density_spin calls compute_density_spin_complex, compute_density_spin_real
adaptive_mix_update calls dw_mix, reset_counts, up_mix
build_hamiltonian_complex calls apply_boundary_conditions_complex, validate_hamiltonian_inputs
check_scf_convergence calls compute_density_norm
compute_total_energy calls get_vxc, get_exc
diagonalize_hermitian_complex calls zheevd
get_vxc calls apply_symmetry_transform, convert_to_nm, determine_region, spline2d_eval
apply_boundary_conditions_complex calls validate_bc_parameters
get_exc calls apply_symmetry_transform, convert_to_nm, determine_region, spline2d_eval
spline2d_eval calls d2y_tmp, f_tmp, find_interval, spline1d_eval, y_tmp
spline1d_eval calls find_interval