solve_linear_system – LSDA-Hubbard-Fortran
solve_linear_system Subroutine
MIT
33 statements
Source File
public subroutine solve_linear_system(A, x, b)
Solves linear system A·x = b using LAPACK DGESV
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: A(:,:)
real(kind=dp), intent(out) :: x(:)
real(kind=dp), intent(in) :: b(:)
Calls
Called by
Call graph
solve_linear_system calls dgesv
solve_newton calls solve_linear_system
compute_e_xc calls solve_newton
sweep_u_backward calls solve_newton
sweep_u_forward calls solve_newton
compute_v_xc_numerical calls compute_e_xc
generate_xc_table calls compute_e_xc, compute_v_xc_numerical
sweep_u_bidirectional calls sweep_u_backward, sweep_u_forward
generate_table_grid calls generate_xc_table