solve_newton – LSDA-Hubbard-Fortran
solve_newton Subroutine
MIT
52 statements
Source File
public subroutine solve_newton(x, I, J, L, U, converged)
Newton-Raphson solver for Bethe Ansatz equations
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(inout) :: x(:)
real(kind=dp), intent(in) :: I(:)
real(kind=dp), intent(in) :: J(:)
integer, intent(in) :: L
real(kind=dp), intent(in) :: U
logical, intent(out) :: converged
Calls
Called by
Call graph
solve_newton calls compute_jacobian, compute_residual, line_search, solve_linear_system
compute_residual calls theta, theta_capital
line_search calls compute_residual
solve_linear_system calls dgesv
compute_e_xc calls solve_newton
sweep_u_backward calls solve_newton
sweep_u_forward calls solve_newton
compute_v_xc_numerical calls compute_e_xc
generate_xc_table calls compute_e_xc, compute_v_xc_numerical
sweep_u_bidirectional calls sweep_u_backward, sweep_u_forward
generate_table_grid calls generate_xc_table