spline2d_init – LSDA-Hubbard-Fortran
spline2d_init Subroutine
MIT
34 statements
Source File
public subroutine spline2d_init(spl, x_grid, y_grid, f_values, n_y_pts)
Initialize 2D spline from grid data
Arguments
Type Intent Optional Attributes Name
type(spline2d_t), intent(out) :: spl
real(kind=dp), intent(in) :: x_grid(:)
real(kind=dp), intent(in) :: y_grid(:,:)
real(kind=dp), intent(in) :: f_values(:,:)
integer, intent(in) :: n_y_pts(:)
Calls
Called by
Source Code
    subroutine spline2d_init(spl, x_grid, y_grid, f_values, n_y_pts)
        type(spline2d_t), intent(out) :: spl
        real(dp), intent(in) :: x_grid(:), y_grid(:,:), f_values(:,:)
        integer, intent(in) :: n_y_pts(:)
        integer :: i, nx, ny_max, ny
        nx = size(x_grid)
        ny_max = size(y_grid, 1)
        spl%n_x = nx
        spl%n_y_max = ny_max
        allocate(spl%x(nx))
        allocate(spl%y(ny_max, nx))
        allocate(spl%f(ny_max, nx))
        allocate(spl%n_y(nx))
        allocate(spl%d2f_dy2(ny_max, nx))
        spl%x = x_grid
        spl%y = y_grid
        spl%f = f_values
        spl%n_y = n_y_pts
        do i = 1, nx
            ny = spl%n_y(i)
            if (ny > 1) then
                ! Create temporary 0-indexed arrays for spline1d_coeff
                block
                    real(dp) :: y_temp(0:ny-1), f_temp(0:ny-1), d2y_temp(0:ny-1)
                    y_temp = spl%y(1:ny, i)
                    f_temp = spl%f(1:ny, i)
                    call spline1d_coeff(y_temp, f_temp, ny-1, d2y_temp, 'natural', 0.0_dp, 0.0_dp)
                    spl%d2f_dy2(1:ny, i) = d2y_temp
                end block
            else
                spl%d2f_dy2(1, i) = 0.0_dp
            end if
        end do
        spl%initialized = .true.
    end subroutine spline2d_init
Call graph
spline2d_init calls d2y_temp, f_temp, spline1d_coeff, y_temp
xc_lsda_init calls spline2d_init