spline1d_eval – LSDA-Hubbard-Fortran
spline1d_eval Function
MIT
21 statements
Source File
private function spline1d_eval(x_grid, y_grid, d2y, n, x) result(y_interp)
Evaluate cubic spline at point x given coefficients
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: x_grid(0:)
real(kind=dp), intent(in) :: y_grid(0:)
real(kind=dp), intent(in) :: d2y(0:)
integer, intent(in) :: n
real(kind=dp), intent(in) :: x
Return Value real(kind=dp)
Calls
Called by
Source Code
    function spline1d_eval(x_grid, y_grid, d2y, n, x) result(y_interp)
        real(dp), intent(in) :: x_grid(0:), y_grid(0:), d2y(0:), x
        integer, intent(in) :: n
        real(dp) :: y_interp, h, a, b
        integer :: i
        if (n == 0) then
            y_interp = y_grid(0)
            return
        end if
        i = find_interval(x_grid, n+1, x)
        if (i < 0) i = 0
        if (i >= n) i = n - 1
        h = x_grid(i+1) - x_grid(i)
        if (abs(h) < 1.0e-15_dp) then
            y_interp = y_grid(i)
            return
        end if
        a = (x_grid(i+1) - x) / h
        b = 1.0_dp - a
        y_interp = a * y_grid(i) + b * y_grid(i+1) + &
                    ((a**3 - a) * h**2 / 6.0_dp) * d2y(i) + &
                    ((b**3 - b) * h**2 / 6.0_dp) * d2y(i+1)
    end function spline1d_eval
Call graph
spline1d_eval calls find_interval
spline2d_eval calls spline1d_eval
get_exc calls spline2d_eval
get_vxc calls spline2d_eval
compute_total_energy calls get_exc, get_vxc
run_kohn_sham_scf_complex calls get_vxc, compute_total_energy
run_kohn_sham_scf_real calls get_vxc, compute_total_energy