sweep_U_bidirectional – LSDA-Hubbard-Fortran
sweep_U_bidirectional Subroutine
MIT
28 statements
Source File
public subroutine sweep_U_bidirectional(I, J, L, U_values, solutions, energies, converged_flags)
Bidirectional sweep with refinement (forward + backward average)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: I(:)
real(kind=dp), intent(in) :: J(:)
integer, intent(in) :: L
real(kind=dp), intent(in) :: U_values(:)
real(kind=dp), intent(out) :: solutions(:,:)
real(kind=dp), intent(out) :: energies(:)
logical, intent(out) :: converged_flags(:)
Calls
Call graph
sweep_u_bidirectional calls sweep_u_backward, sweep_u_forward
sweep_u_backward calls compute_energy, estimate_dxdu, solve_newton
sweep_u_forward calls compute_energy, estimate_dxdu, solve_newton
solve_newton calls compute_jacobian, compute_residual, line_search, solve_linear_system
compute_residual calls theta, theta_capital
line_search calls compute_residual
solve_linear_system calls dgesv