xc_lsda_init – LSDA-Hubbard-Fortran
xc_lsda_init Subroutine
MIT
32 statements
Source File
public subroutine xc_lsda_init(xc, table_file, ierr)
Initialize XC functional from table file
Arguments
Type Intent Optional Attributes Name
type(xc_lsda_t), intent(out) :: xc
character(len=*), intent(in) :: table_file
integer, intent(out) :: ierr
Calls
Source Code
    subroutine xc_lsda_init(xc, table_file, ierr)
        type(xc_lsda_t), intent(out) :: xc
        character(len=*), intent(in) :: table_file
        integer, intent(out) :: ierr
        type(xc_table_t) :: table
        integer :: io_stat
        integer, allocatable :: n_y_pts(:)
        integer :: i
        ierr = ERROR_SUCCESS
        call read_fortran_table(table_file, table, io_stat)
        if (io_stat /= 0) then
            print *, "ERROR: Failed to read table file: ", trim(table_file)
            ierr = ERROR_FILE_READ
            return
        end if
        xc%U = table%U
        ! Create n_y_pts array (same for all n_grid points in current implementation)
        allocate(n_y_pts(table%n_points_n))
        do i = 1, table%n_points_n
            n_y_pts(i) = table%n_points_m
        end do
        call spline2d_init(xc%spl_exc, table%n_grid, table%m_grid, &
                           table%exc, n_y_pts)
        call spline2d_init(xc%spl_vxc_up, table%n_grid, table%m_grid, &
                           table%vxc_up, n_y_pts)
        call spline2d_init(xc%spl_vxc_down, table%n_grid, table%m_grid, &
                           table%vxc_down, n_y_pts)
        deallocate(n_y_pts)
        if (.not. xc%spl_exc%initialized .or. &
            .not. xc%spl_vxc_up%initialized .or. &
            .not. xc%spl_vxc_down%initialized) then
            ierr = ERROR_SPLINE_INITIALIZATION_FAILED
            call deallocate_table(table)
            return
        end if
        xc%initialized = .true.
        call deallocate_table(table)
    end subroutine xc_lsda_init
Call graph
xc_lsda_init calls deallocate_table, read_fortran_table, spline2d_init
read_fortran_table calls deallocate_table
spline2d_init calls d2y_temp, f_temp, spline1d_coeff, y_temp