compute_density_spin – LSDA-Hubbard-Fortran
compute_density_spin Interface
MIT
4 statements
Source File
public interface compute_density_spin
Calls
Called by
Module Procedures
private subroutine compute_density_spin_real(eigvecs, L, n_elec, density, ierr)
Compute density from real eigenvectors (Open/Periodic BC)
Read more…
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: eigvecs(:,:)
integer, intent(in) :: L
integer, intent(in) :: n_elec
real(kind=dp), intent(out) :: density(:)
integer, intent(out) :: ierr
private subroutine compute_density_spin_complex(eigvecs, L, n_elec, density, ierr)
Compute density from complex eigenvectors (Twisted BC)
Read more…
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: eigvecs(:,:)
integer, intent(in) :: L
integer, intent(in) :: n_elec
real(kind=dp), intent(out) :: density(:)
integer, intent(out) :: ierr
Call graph
compute_density_spin calls compute_density_spin_complex, compute_density_spin_real
run_kohn_sham_scf_complex calls compute_density_spin
run_kohn_sham_scf_real calls compute_density_spin