DSYEVD – LSDA-Hubbard-Fortran
DSYEVD Interface
MIT
32 statements
Source File
interface
Called by
private subroutine DSYEVD(jobz, uplo, n, a, lda, w, work, lwork, iwork, liwork, info)
Arguments
Type Intent Optional Attributes Name
character(len=1), intent(in) :: jobz
character(len=1), intent(in) :: uplo
integer, intent(in) :: n
real(kind=dp), intent(inout) :: a(lda,*)
integer, intent(in) :: lda
real(kind=dp), intent(out) :: w(*)
real(kind=dp), intent(out) :: work(*)
integer, intent(in) :: lwork
integer, intent(out) :: iwork(*)
integer, intent(in) :: liwork
integer, intent(out) :: info
Call graph
diagonalize_symmetric_real calls dsyevd
diagonalize_symmetric_real_values_only calls dsyevd
run_kohn_sham_scf_real calls diagonalize_symmetric_real