ZHEEVD – LSDA-Hubbard-Fortran
ZHEEVD Interface
MIT
32 statements
Source File
interface
Called by
private subroutine ZHEEVD(jobz, uplo, n, a, lda, w, work, lwork, rwork, lrwork, iwork, liwork, info)
Arguments
Type Intent Optional Attributes Name
character(len=1), intent(in) :: jobz
character(len=1), intent(in) :: uplo
integer, intent(in) :: n
complex(kind=dp), intent(inout) :: a(lda,*)
integer, intent(in) :: lda
real(kind=dp), intent(out) :: w(*)
complex(kind=dp), intent(out) :: work(*)
integer, intent(in) :: lwork
real(kind=dp), intent(out) :: rwork(*)
integer, intent(in) :: lrwork
integer, intent(out) :: iwork(*)
integer, intent(in) :: liwork
integer, intent(out) :: info
Call graph
diagonalize_hermitian_complex calls zheevd
diagonalize_hermitian_complex_values_only calls zheevd
run_kohn_sham_scf_complex calls diagonalize_hermitian_complex